name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [16.x, 18.x, 20.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install

      - if: matrix.os == 'ubuntu-latest'
        run: xvfb-run yarn test
      - if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        run: yarn test
